"""add exam_name to exams

Revision ID: 5f53bad1ea5b
Revises: d995a7e3b2ae
Create Date: 2026-04-28 12:05:25.564770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f53bad1ea5b'
down_revision = 'd995a7e3b2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_name', sa.String(length=200), nullable=True))
        batch_op.alter_column('exam_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.alter_column('exam_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('exam_name')

    # ### end Alembic commands ###
