name: Deploy Mecha School to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy on VPS
    runs-on: self-hosted

    steps:
      - name: Run deploy script locally on VPS
        run: |
          bash /root/deploy-mecha.sh
